---
- hosts: kubernetes-master
  become: yes
  vars_files:
  - app_env_variables
  tasks:

  - name: Add Helm Repo
    shell: helm repo add helm https://saikrishna2681.jfrog.io/artifactory/sai2681/ --username admin --password admin123

  - name: Update Helm Repo
    shell: helm repo update
  
  - name: Create Secret 
    shell: sudo kubectl create secret docker-registry regcred --docker-server=https://saikrishna2681.jfrog.io --docker-username=admin --docker-password=amin123
    
  - name: Install Helm Chart
    shell: helm install sai2681/webapp2 --generate-name
