---
- hosts: kubernetes-master-nodes
  become: yes
  
  tasks:
  
  - name: Helm version
    shell: helm version
    
  - name: Add Helm Repo
    shell: helm repo add helm https://saikrishna2681.jfrog.io/artifactory/saicharts/ --username admin --password admin123

  - name: Update Helm Repo
    shell: helm repo update
  
  - name: Create Secret 
    shell: sudo kubectl create secret docker-registry regcred --docker-server=https://saikrishna2681.jfrog.io/artifactory/sai2681/ --docker-username=admin --docker-password=admin123
    
  - name: Install Helm Chart
    shell: helm install saicharts/webapp --generate-name
 
