---
- hosts: kubernetes-master
  become: yes
  tasks:
  - name: Helm version
    shell: helm version
  - name: Add Helm Repo
    shell: helm repo add helm https://saikrishna2681.jfrog.io/artifactory/helm --username admin --password admin123
  - name: PWD
    shell: pwd
  - name: list
    shell: ls -a
  - name: Update Helm Repo
    shell: helm repo update
  - name: Install Helm Chart
    shell: helm install helm/webapp --generate-name
