version: '2'
services:
  web:
    build: .
    image: 2681/webapp
    ports:
      - "9080:8080"
    volumes:
    - /var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: mysql/mysql-server:5.7
    image: 2681/mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'hello_java'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'demo_java'
      # You can use whatever password you like
      MYSQL_PASSWORD: '1234'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
