---
- name:  Install Tomcat
  hosts: apache
  gather_facts: false
  become: yes
  tasks:
  - name: Installing req Java
    get_url:
      url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.34/bin/apache-tomcat-9.0.34.tar.gz
      dest: /opt/tomcat
  - name: Extract
    unarchive:
      src: /opt/tomcat/apache-tomcat-9.0.34.tar.gz
      dest: /opt/tomcat
    remote_src: yes
