---
- name:  Install Tomcat
  hosts: apache
  gather_facts: false
  become: yes
  vars:
    tomcat_user: 8089
  tasks:
  - name: Installing req Java
    get_url:
      url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.34/bin/apache-tomcat-9.0.34.tar.gz
      dest: /opt/tomcat
  - name: Extract
    unarchive:
      src: /opt/tomcat/apache-tomcat-9.0.34.tar.gz
      dest: /opt/tomcat
      remote_src: yes
#  - name: Renaming Tomcat
#    command: mv /opt/tomcat/apache-tomcat-9.0.34 /opt/tomcat/latest
  - name: Rplacing default port
    template:
      src: server.xml.j2
      dest: /opt/tomcat/latest/server.xml
  - name: start tomcat
    shell:  nohup /opt/tomcat/latest/bin/startup.sh &
