---
- name:  Install Tomcat
  hosts: apache
  gather_facts: false
  become: yes
  vars:
    tomcat_port: 8089
    tomcat_user: tomcat
    tomcat_password: tomcat123
  tasks:
  - name: Installing tomcat
    get_url:
      url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.34/bin/apache-tomcat-9.0.34.tar.gz
      dest: /opt/tomcat
  - name: Extract
    unarchive:
      src: /opt/tomcat/apache-tomcat-9.0.34.tar.gz
      dest: /opt/tomcat
      remote_src: yes
#  - name: Renaming Tomcat
#    command: mv /opt/tomcat/apache-tomcat-9.0.34 /opt/tomcat/latest
  - name: Rplacing default port
    template:
      src: server.xml.j2
      dest: /opt/tomcat/apache-tomcat-9.0.34/conf/server.xml
  - name: Rplacing tomcat user
    template:
      src: tomcat-users.xml.j2
      dest: /opt/tomcat/apache-tomcat-9.0.34/conf/tomcat-users.xml
  - name: tomcat manager app from diffrent host
    template:
      src: context.xml.j2
      dest: /opt/tomcat/apache-tomcat-9.0.34/webapps/manager/META-INF/context.xml
  - name: remove old files
    file: 
      path: /opt/tomcat/apache-tomcat-9.0.34/webapps/Maven*
      state: absent
  - name: download from artifactory server
#    maven_artifact:
#      repository_url: http://3.15.201.98:8082/artifactory/libs-snapshot-local/MyWebapp/MavenWebApp
#      username: admin
#      password: password123
#      dest: /opt/app/
    get_url:
      url:  http://3.19.72.157:8082/artifactory/libs-snapshot-local/MyWebapp/MavenWebApp/0.0.2-SNAPSHOT/MavenWebApp-0.0.2-SNAPSHOT.war
      dest: /opt/tomcat/apache-tomcat-9.0.34/webapps/
      username: admin
      password: password123
  - name: start tomcat
    shell:  nohup /opt/tomcat/apache-tomcat-9.0.34/bin/catalina.sh start &
